language: php

php:
    - 5.5.9
    - 5.6
    - 7.0

before_script:
    - sudo apt-get update
    - sudo apt-get upgrade
    - php -v
    - composer self-update --quiet
    - composer install --prefer-source --no-interaction --dev
    - composer update --prefer-source --no-interaction --dev